In [1]:
import pandas as pd
import pickle

In [2]:
import os

DATA_DIR = 'data/train-scene classification'
MODEL_DIR = "saved_model/"

IMG_DIR = os.path.join(DATA_DIR, 'train')

TRAIN_CSV = os.path.join(DATA_DIR, 'train.csv')
TEST_CSV = "data/test_WyRytb0.csv"

RESULTS = "results/"

image = 'image_name'
label = 'label'

numpy_dir = "numpy_outs/"

H = W = 150
ORIG_H = ORIG_W = 150

In [3]:
# from utlities import stratified_split
#generate metadata
# stratified_split(TRAIN_CSV,"k_fold_metadata")

In [4]:
test_data = pd.read_csv(TEST_CSV)

In [5]:
from PIL import Image
img = Image.open("data/train-scene classification/train/"+"2.jpg")
img.size

(150, 150)

In [6]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch
import torchvision.transforms.functional as Func
from torch.utils import data
from torchvision import transforms, utils

import tqdm
from torch.autograd import Variable
from sklearn.model_selection import train_test_split

class AVDataset(data.Dataset):
    def __init__(self, IMG_DIR, file_list, is_test = False, transform=None):
        self.is_test = is_test
        self.root_path = IMG_DIR
        self.file_list = file_list
        self.transform = transform
    
    def __len__(self):
        return len(self.file_list)
    
    def __getitem__(self, index):
        if index not in range(0, len(self.file_list)):
            return self.__getitem__(np.random.randint(0, self.__len__()))
        
        file_id = self.file_list[index]
        
        image_path = os.path.join(self.root_path, file_id[0])
        
        image = load_image(image_path)
        if self.transform:
            image = self.transform(image)
            
        if self.is_test==True:
            return image
        else:
            return image,file_id[1]

In [7]:
no_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
                                   ])
train_transforms = transforms.Compose([
    transforms.RandomHorizontalFlip(p=1.0),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
])
train_transforms2 = transforms.Compose([
    transforms.ColorJitter(brightness=0.4, contrast=0.2, saturation=0.5, hue=0.3),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
])
train_transforms3 = transforms.Compose([
    transforms.RandomHorizontalFlip(p=1.0),
    transforms.ColorJitter(brightness=0.4, contrast=0.2, saturation=0.5, hue=0.3),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
])

In [8]:
%matplotlib inline
import cv2
from PIL import Image
import matplotlib.pyplot as plt
def load_image(path):
    img = cv2.imread(str(path))
    img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    if img.shape != (H,W,3):
        img = cv2.resize(img, (H,W), interpolation = cv2.INTER_AREA)
    return Image.fromarray(img)

In [9]:
def create_file_list(dataframe):
    return [tuple(x) for x in dataframe.values]

In [10]:
import torch
from torch import nn
from pathlib import Path
from torch.nn import functional as F
from torchvision import models
from torchvision.transforms import ToTensor, Normalize, Compose
import cv2
from pathlib import Path

In [11]:
from cnn_finetune import make_model
model = make_model('resnet34', num_classes=6, pretrained=True, input_size=(150, 150))


In [12]:
import torch
from torchvision import models
from torchsummary import summary
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
vgg = model.to(device)


# summary(vgg, (3, 150, 150))

In [13]:
def save_checkpoint(state, is_best,filename):
#     filename='saved_model/best_acc.pth.tar'
    """Save checkpoint if a new best is achieved"""
    if is_best:
        print ("=> Saving a new best")
        torch.save(state, filename)  # save checkpoint
    else:
        print ("=> Validation loss did not improve")

In [14]:
from sklearn.metrics import accuracy_score, classification_report , confusion_matrix
def train_data(train_dataloader,val_dataloader, filename):
    best_acc=0.0
    model = make_model('resnet50', num_classes=6, pretrained=True, input_size=(150, 150), dropout_p=0.5)
    model = model.to(device)
    learning_rate = 1e-3
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate,momentum=0.9)
    criterion =  nn.CrossEntropyLoss()
    epoch=10
    for e in range(epoch):
    #     learning_rate = cyclic_lr(e)
        print("learning_rate",learning_rate)
        train_loss = []
        train_preds = []
        train_truth = []
        for image, mask in tqdm.tqdm(train_dataloader):

            optimizer.zero_grad()

            image = image.type(torch.FloatTensor).cuda()
            y_pred = model(Variable(image))
            loss = criterion(y_pred, Variable(mask.cuda()))

            _,predicted = torch.max(y_pred,1)
            train_preds.extend(predicted.cpu().data.numpy())
            train_truth.extend(mask.cpu().data.numpy())

            loss.backward()

            optimizer.step()
            train_loss.append(loss.item())

        val_loss = []
        val_preds = []
        val_truth = []
        for image, mask in val_dataloader:
            image = image.type(torch.FloatTensor).cuda()
            y_pred = model(Variable(image))

            _,predicted = torch.max(y_pred,1)
            val_preds.extend(predicted.cpu().data.numpy())
            val_truth.extend(mask.cpu().data.numpy())

            loss = criterion(y_pred, Variable(mask.cuda()))
            val_loss.append(loss.item())
        
        train_acc = accuracy_score(train_truth,train_preds)
        val_acc = accuracy_score(val_truth,val_preds)
        print("Epoch: %d, Train loss: %.3f,  Val loss: %.3f" % (e, np.mean(train_loss), np.mean(val_loss)))
        print("Train acc: %.3f, Val acc: %.3f" %(train_acc, val_acc))
#         print("Classification report" , classification_report(val_truth, val_preds))
        print("Confusion report" , confusion_matrix(val_truth, val_preds))
        
        is_best = bool(val_acc>best_acc)
        best_acc = max(val_acc,best_acc)
        save_checkpoint({
            'epoch': e + 1,
            'state_dict': model.state_dict(),
            'best_acc': best_acc
        }, is_best, filename)

In [15]:
for i in range(0,10):
    print("*"*20, "Fold", i,"*"*10)
    train = pd.read_csv("k_fold_metadata/train_{}.csv".format(i))
    val = pd.read_csv("k_fold_metadata/val_{}.csv".format(i))
    file_list_train = create_file_list(train)
    file_list_val = create_file_list(val)
    dataset = torch.utils.data.ConcatDataset([AVDataset(IMG_DIR, file_list_train, transform=train_transforms),
                                              AVDataset(IMG_DIR, file_list_train, transform=no_transforms),
                                              AVDataset(IMG_DIR, file_list_train, transform=train_transforms2),
                                              AVDataset(IMG_DIR, file_list_train, transform=train_transforms3)])
    val_dataset = torch.utils.data.ConcatDataset([AVDataset(IMG_DIR, file_list_val,transform=no_transforms),
                                                  AVDataset(IMG_DIR, file_list_val,transform=train_transforms),
                                                  AVDataset(IMG_DIR, file_list_val,transform=train_transforms2),
                                                  AVDataset(IMG_DIR, file_list_val,transform=train_transforms3)])
    train_dataloader = data.DataLoader(dataset, batch_size = 16,shuffle=True, num_workers=8)
    val_dataloader = data.DataLoader(val_dataset, batch_size = 8, shuffle = False, num_workers=4)
    train_data(train_dataloader, val_dataloader, "saved_model/resnet50/model_{}.pth.tar".format(i))

******************** Fold 0 **********


  0%|          | 0/3449 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.255,  Val loss: 0.391
Train acc: 0.910, Val acc: 0.883
Confusion report [[767   6   5   4  13 153]
 [  1 959   9   7   1  11]
 [  0   9 950  68  36   5]
 [  1  17 187 875  13   3]
 [  8   5  56  34 894   7]
 [ 33  10   7   0   7 983]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.102,  Val loss: 0.388
Train acc: 0.964, Val acc: 0.896
Confusion report [[826   3   1   0  15 103]
 [  0 960  12   5   1  10]
 [  0   8 889 115  50   6]
 [  2   8 125 936  24   1]
 [ 19   4  14  34 925   8]
 [ 55   7   2   1   3 972]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.052,  Val loss: 0.420
Train acc: 0.982, Val acc: 0.902
Confusion report [[811   5   2   4  18 108]
 [  0 966   7   8   5   2]
 [  1   7 902 120  38   0]
 [  3  12  98 975   8   0]
 [  5   3  15  43 938   0]
 [ 54  13   4   2  15 952]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.033,  Val loss: 0.474
Train acc: 0.989, Val acc: 0.901
Confusion report [[813   3   5   2  21 104]
 [  0 975   2   0   5   6]
 [  1  11 928  94  33   1]
 [  3  31 112 915  32   3]
 [  9  10  25  23 933   4]
 [ 51   8   6   1   2 972]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.026,  Val loss: 0.462
Train acc: 0.991, Val acc: 0.902
Confusion report [[828   1   4   2   9 104]
 [  0 967  10   4   2   5]
 [  0   1 949  83  32   3]
 [  4   6 135 927  18   6]
 [ 14   0  49  28 911   2]
 [ 67   1   7   2   3 960]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 5, Train loss: 0.017,  Val loss: 0.452
Train acc: 0.994, Val acc: 0.912
Confusion report [[ 835    2    0    1   10  100]
 [   1  979    0    4    0    4]
 [   0    3  915  125   25    0]
 [   2   12   72 1001    8    1]
 [  15    2   28   44  909    6]
 [  64   11    0    0    1  964]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.014,  Val loss: 0.485
Train acc: 0.995, Val acc: 0.913
Confusion report [[823   1   0   1  16 107]
 [  1 979   1   3   1   3]
 [  1   6 928 101  30   2]
 [  0  16  97 964  17   2]
 [  6   2  18  38 936   4]
 [ 51   6   0   2   0 981]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.010,  Val loss: 0.505
Train acc: 0.996, Val acc: 0.908
Confusion report [[810   2   2   1  16 117]
 [  0 977   1  10   0   0]
 [  0  11 929 105  23   0]
 [  4  11 112 953   8   8]
 [  5   0  21  42 935   1]
 [ 53   2   2   0   7 976]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.010,  Val loss: 0.482
Train acc: 0.997, Val acc: 0.903
Confusion report [[845   2   0   1  11  89]
 [  0 974   1   3   0  10]
 [  0  10 926 106  24   2]
 [  6  16 104 949  18   3]
 [  9   2  21  31 940   1]
 [118   0   2   2   1 917]]
=> Validation loss did not improve
learning_rate 0.001


100%|██████████| 3449/3449 [15:24<00:00,  3.73it/s]


Epoch: 9, Train loss: 0.011,  Val loss: 0.543
Train acc: 0.996, Val acc: 0.912
Confusion report [[823   4   1   0  11 109]
 [  0 987   1   0   0   0]
 [  1   7 926 116  17   1]
 [  0  19 100 964  10   3]
 [  5   7  26  40 926   0]
 [ 47   4   5   2   4 978]]
=> Validation loss did not improve
******************** Fold 1 **********


  0%|          | 0/3449 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.253,  Val loss: 0.385
Train acc: 0.910, Val acc: 0.872
Confusion report [[897   3   5   5   2  36]
 [  2 968   2  10   1   5]
 [  2  17 822 188  32   3]
 [ 11  25 102 914  38   6]
 [ 16  22  37  45 874  10]
 [103  17  14   4  20 882]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.100,  Val loss: 0.412
Train acc: 0.965, Val acc: 0.896
Confusion report [[874   0   3   3   2  66]
 [  8 952   6  13   2   7]
 [  0   9 902 127  25   1]
 [  4  19 124 913  30   6]
 [ 18   9  41  29 901   6]
 [ 46   8   7   2  17 960]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.054,  Val loss: 0.487
Train acc: 0.981, Val acc: 0.895
Confusion report [[858   6  12   2   6  64]
 [  1 977   6   3   0   1]
 [  0  16 934  94  20   0]
 [  5  18 160 888  21   4]
 [ 10  14  41  37 897   5]
 [ 52  12  14   1  22 939]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.035,  Val loss: 0.487
Train acc: 0.988, Val acc: 0.895
Confusion report [[843   5  13   5   3  79]
 [  3 970   5   6   0   4]
 [  1  13 898 127  25   0]
 [  5  12 113 932  33   1]
 [ 13  15  46  30 894   6]
 [ 47  12   9   4   9 959]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.025,  Val loss: 0.506
Train acc: 0.991, Val acc: 0.900
Confusion report [[888   3   5   4   4  44]
 [  2 961   6   7   0  12]
 [  2  17 911 120  13   1]
 [  9  17 123 926  19   2]
 [ 19  16  36  42 884   7]
 [ 59  10   6   1   7 957]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 5, Train loss: 0.018,  Val loss: 0.515
Train acc: 0.994, Val acc: 0.904
Confusion report [[903   0   2   2   1  40]
 [  0 968   3   5   3   9]
 [  3  15 912 110  24   0]
 [ 12  16 143 897  26   2]
 [ 17  14  32  20 915   6]
 [ 53   4   9   1  16 957]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.015,  Val loss: 0.523
Train acc: 0.995, Val acc: 0.901
Confusion report [[861   0   0   6   3  78]
 [  6 956   2  16   0   8]
 [  0  12 882 149  18   3]
 [  5  14  95 947  32   3]
 [ 17   7  27  40 901  12]
 [ 30   5  10   0  10 985]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.013,  Val loss: 0.550
Train acc: 0.995, Val acc: 0.905
Confusion report [[861   2   1   1   1  82]
 [  5 962   2  10   0   9]
 [  5   9 903 126  20   1]
 [  9  11 101 932  36   7]
 [ 18   9  27  26 904  20]
 [ 30   5   1   1   8 995]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.010,  Val loss: 0.530
Train acc: 0.997, Val acc: 0.907
Confusion report [[871   1   2   3   4  67]
 [  2 966   5  11   0   4]
 [  1  12 927 106  17   1]
 [  4   6 127 928  25   6]
 [ 16   7  36  37 899   9]
 [ 32  10   9   3   7 979]]
=> Saving a new best
learning_rate 0.001


100%|██████████| 3449/3449 [15:24<00:00,  3.73it/s]


Epoch: 9, Train loss: 0.008,  Val loss: 0.569
Train acc: 0.997, Val acc: 0.908
Confusion report [[874   1   5   5   6  57]
 [  4 961   2  13   3   5]
 [  1   7 897 153   5   1]
 [  2  13 104 947  28   2]
 [  8  11  25  30 920  10]
 [ 29  13   8   0  12 978]]
=> Saving a new best
******************** Fold 2 **********


  0%|          | 0/3449 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.253,  Val loss: 0.407
Train acc: 0.910, Val acc: 0.876
Confusion report [[826  12   7   9  10  84]
 [  3 935   8  17  14  11]
 [ 15   6 893 109  34   7]
 [ 11   9 168 879  24   5]
 [ 13   7  45  26 891  22]
 [ 52   5   6   7  13 957]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.101,  Val loss: 0.455
Train acc: 0.965, Val acc: 0.884
Confusion report [[819   6  13   3  13  94]
 [  2 942   7  23   2  12]
 [ 12  15 845 145  39   8]
 [  7   9 126 915  36   3]
 [  6   9  22  25 932  10]
 [ 34  10   7   1  16 972]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.053,  Val loss: 0.515
Train acc: 0.982, Val acc: 0.888
Confusion report [[835  17  14   3  11  68]
 [  1 964   4  15   3   1]
 [ 14  17 897 108  23   5]
 [  5  14 156 893  26   2]
 [ 11  13  31  26 920   3]
 [ 60  17   5   2  14 942]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.035,  Val loss: 0.505
Train acc: 0.988, Val acc: 0.890
Confusion report [[841   3  15   1  13  75]
 [  1 958   3  12   5   9]
 [ 12  16 881 127  22   6]
 [  3  15 159 888  30   1]
 [  7  13  37  27 914   6]
 [ 32   9   8   2   6 983]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.024,  Val loss: 0.562
Train acc: 0.992, Val acc: 0.891
Confusion report [[810   6  12   6   4 110]
 [  0 958   6  15   3   6]
 [  7  13 897 112  25  10]
 [ 10  10 164 882  28   2]
 [  9   8  18  28 935   6]
 [ 28   5   8   1  10 988]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 5, Train loss: 0.015,  Val loss: 0.562
Train acc: 0.995, Val acc: 0.894
Confusion report [[835  10   9   1  12  81]
 [  0 970   0  13   3   2]
 [ 11  21 854 142  29   7]
 [  7  21 106 926  35   1]
 [  7  16  20  22 933   6]
 [ 32  14   7   3  14 970]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.014,  Val loss: 0.565
Train acc: 0.995, Val acc: 0.893
Confusion report [[861   5   7   0  13  62]
 [  1 959   1  15   6   6]
 [ 14  15 902 116  13   4]
 [  9  11 169 887  18   2]
 [ 11  13  47  21 910   2]
 [ 44   9   7   4  10 966]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.015,  Val loss: 0.540
Train acc: 0.995, Val acc: 0.900
Confusion report [[829   5   9   0   5 100]
 [  0 962   4  16   3   3]
 [ 13  11 897 112  20  11]
 [  5  12 123 934  18   4]
 [  8  11  25  32 921   7]
 [ 26  10  10   1   8 985]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.009,  Val loss: 0.597
Train acc: 0.997, Val acc: 0.900
Confusion report [[867   4   7   2   3  65]
 [  4 958   3  17   3   3]
 [ 18  14 885 117  21   9]
 [ 10   8 124 925  28   1]
 [  7  10  33  27 923   4]
 [ 49   7   4   4   8 968]]
=> Validation loss did not improve
learning_rate 0.001


100%|██████████| 3449/3449 [15:24<00:00,  3.73it/s]


Epoch: 9, Train loss: 0.008,  Val loss: 0.594
Train acc: 0.997, Val acc: 0.894
Confusion report [[836  10  10   2   9  81]
 [  0 962   4  16   1   5]
 [  7  14 902 115  18   8]
 [  5  10 147 905  25   4]
 [  6   9  48  28 908   5]
 [ 35   8   6   5  11 975]]
=> Validation loss did not improve
******************** Fold 3 **********


  0%|          | 0/3449 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.251,  Val loss: 0.456
Train acc: 0.910, Val acc: 0.870
Confusion report [[810   4   5   8   7 114]
 [ 12 932  10  14   5  15]
 [  9   5 895 108  41   6]
 [ 13  20 170 832  50   7]
 [ 21  17  28  22 905  11]
 [ 47   4  12   6   5 966]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.095,  Val loss: 0.542
Train acc: 0.967, Val acc: 0.879
Confusion report [[825   3   2  10   9  99]
 [  6 948   9   9  10   6]
 [ 12  11 858 148  35   0]
 [ 10  16 117 869  67  13]
 [ 19   9  14  16 937   9]
 [ 51   7   2  11  12 957]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.054,  Val loss: 0.565
Train acc: 0.981, Val acc: 0.891
Confusion report [[843   2   4   8  10  81]
 [  6 951   7  14   5   5]
 [  6  11 880 123  40   4]
 [ 13  12 116 906  42   3]
 [ 10  14  20  22 934   4]
 [ 48  12   6  10  13 951]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.034,  Val loss: 0.622
Train acc: 0.989, Val acc: 0.886
Confusion report [[857   3   2   9  10  67]
 [  7 948   5  14   3  11]
 [ 15   7 900 115  25   2]
 [ 10  15 151 871  40   5]
 [ 12  16  33  18 916   9]
 [ 75   5   3   9   6 942]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.024,  Val loss: 0.660
Train acc: 0.992, Val acc: 0.887
Confusion report [[866   5   3   6  13  55]
 [  6 962   5  10   0   5]
 [  7  12 889 123  31   2]
 [ 14  16 139 877  45   1]
 [ 25  17  21  16 920   5]
 [ 80  12   4   9   5 930]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 5, Train loss: 0.017,  Val loss: 0.685
Train acc: 0.994, Val acc: 0.890
Confusion report [[850  12   2   8  14  62]
 [  4 968   3  10   1   2]
 [  8  14 903 111  28   0]
 [  4  27 121 915  23   2]
 [ 12  20  32  43 894   3]
 [ 60  24   4   8  12 932]]
=> Validation loss did not improve
learning_rate 0.001


100%|██████████| 3449/3449 [15:20<00:00,  3.75it/s]


Epoch: 6, Train loss: 0.013,  Val loss: 0.705
Train acc: 0.995, Val acc: 0.902
Confusion report [[849   7   0   8   4  80]
 [  4 959   5  12   2   6]
 [  7   9 907 112  28   1]
 [  7  15 116 908  40   6]
 [ 12  12  20  18 935   7]
 [ 40  11   1   4   7 977]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.011,  Val loss: 0.712
Train acc: 0.996, Val acc: 0.902
Confusion report [[850   5   1  11   6  75]
 [  5 964   3  10   1   5]
 [  8   9 932  89  26   0]
 [  5  17 132 902  33   3]
 [ 14  16  17  23 922  12]
 [ 49   9   3  10   3 966]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.012,  Val loss: 0.730
Train acc: 0.996, Val acc: 0.895
Confusion report [[841   8   2  13   3  81]
 [  3 956   2   9  12   6]
 [  9  12 884 132  27   0]
 [  8  21 118 902  36   7]
 [ 16   7  17  16 942   6]
 [ 47   9   4   2  13 965]]
=> Validation loss did not improve
learning_rate 0.001


100%|██████████| 3449/3449 [15:20<00:00,  3.75it/s]


Epoch: 9, Train loss: 0.007,  Val loss: 0.738
Train acc: 0.998, Val acc: 0.896
Confusion report [[875   4   1   3   4  61]
 [  6 950   2  14   6  10]
 [ 10  11 919 100  24   0]
 [  8  14 150 878  32  10]
 [ 18   8  23  23 925   7]
 [ 68   6   7   2   8 949]]
=> Validation loss did not improve
******************** Fold 4 **********


  0%|          | 0/3449 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.254,  Val loss: 0.490
Train acc: 0.908, Val acc: 0.853
Confusion report [[872   2  13   5  23  33]
 [ 16 922  12  16  10  12]
 [  3  15 912  89  37   8]
 [ 13  13 233 740  83  10]
 [ 10   3  45  28 918   0]
 [123   6  11   4  23 873]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.101,  Val loss: 0.523
Train acc: 0.964, Val acc: 0.872
Confusion report [[848   7   6   8  18  61]
 [  0 958   7  10   8   5]
 [ 11  14 808 178  44   9]
 [ 12  27 113 860  72   8]
 [ 18   8  20  30 927   1]
 [ 53   9   9   6  11 952]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.057,  Val loss: 0.542
Train acc: 0.980, Val acc: 0.880
Confusion report [[866   8   8   7  11  48]
 [  0 960   3  18   4   3]
 [ 11  21 861 146  19   6]
 [ 11  17 122 871  66   5]
 [  9   6  33  32 923   1]
 [ 91  13   8   7   3 918]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.033,  Val loss: 0.601
Train acc: 0.989, Val acc: 0.886
Confusion report [[850   3  12   3  12  68]
 [  0 961   5  13   2   7]
 [  7  14 859 146  31   7]
 [  9  20 126 870  55  12]
 [  6   6  27  29 934   2]
 [ 56  11   3   4   5 961]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.024,  Val loss: 0.603
Train acc: 0.992, Val acc: 0.890
Confusion report [[841   4  21   1  14  67]
 [  0 970   0  12   3   3]
 [  3  17 908 100  28   8]
 [  9  25 131 858  60   9]
 [  8   6  32  29 926   3]
 [ 34  22   9   7  11 957]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 5, Train loss: 0.016,  Val loss: 0.674
Train acc: 0.995, Val acc: 0.889
Confusion report [[866   1   3   2  10  66]
 [  2 954   7   9   6  10]
 [  6  12 901 112  25   8]
 [  9  15 149 843  66  10]
 [  8   0  35  29 929   3]
 [ 56   4   5   6   9 960]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.015,  Val loss: 0.630
Train acc: 0.995, Val acc: 0.890
Confusion report [[870   5   5   3  11  54]
 [  1 965   7   8   5   2]
 [  7  11 914 108  16   8]
 [  6  25 155 839  54  13]
 [  6   5  46  22 921   4]
 [ 68   7   3  11   2 949]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.009,  Val loss: 0.662
Train acc: 0.997, Val acc: 0.894
Confusion report [[869   6   3   2  15  53]
 [  3 969   4   6   4   2]
 [  9  16 896 113  25   5]
 [ 11  21 133 863  55   9]
 [  9   1  23  26 945   0]
 [ 70   6   2   6  10 946]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3449 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.011,  Val loss: 0.689
Train acc: 0.996, Val acc: 0.890
Confusion report [[876   9   2   2  14  45]
 [  1 956   7  11   5   8]
 [  7  15 903 115  18   6]
 [ 10  23 143 865  39  12]
 [  9   6  32  26 924   7]
 [ 75   6   6   2  11 940]]
=> Validation loss did not improve
learning_rate 0.001


100%|██████████| 3449/3449 [15:20<00:00,  3.75it/s]


Epoch: 9, Train loss: 0.013,  Val loss: 0.698
Train acc: 0.996, Val acc: 0.887
Confusion report [[857   5   2   3   8  73]
 [  1 969   2   9   5   2]
 [  6  17 879 128  28   6]
 [  5  21 139 878  40   9]
 [  9   3  39  51 899   3]
 [ 52   8   6  10   6 958]]
=> Validation loss did not improve
******************** Fold 5 **********


  0%|          | 0/3450 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.254,  Val loss: 0.480
Train acc: 0.910, Val acc: 0.860
Confusion report [[819   7   8  14  18  78]
 [ 10 926   8  14  13  17]
 [  4   3 810 217  28   2]
 [  8  13 106 892  68   5]
 [ 11   0  18  39 928   8]
 [ 74  15  10   2  42 893]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.103,  Val loss: 0.518
Train acc: 0.964, Val acc: 0.867
Confusion report [[861   8   8   4  14  49]
 [ 10 942  12   9   5  10]
 [  6   2 912 123  19   2]
 [ 21  30 185 792  56   8]
 [  8   9  17  45 910  15]
 [ 97  26   6   2  12 893]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.053,  Val loss: 0.560
Train acc: 0.982, Val acc: 0.880
Confusion report [[865   7   8   4   5  55]
 [ 13 943   6   8   5  13]
 [  7   3 891 138  24   1]
 [ 15  30 132 843  60  12]
 [  8   8  14  34 935   5]
 [ 85  13   6   2  14 916]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.035,  Val loss: 0.627
Train acc: 0.988, Val acc: 0.881
Confusion report [[846  11   7   6  16  58]
 [ 10 945   6  11   4  12]
 [  4   1 922 119  18   0]
 [ 19  23 162 823  58   7]
 [  4   9  13  40 933   5]
 [ 61  17   4   2  22 930]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.026,  Val loss: 0.627
Train acc: 0.991, Val acc: 0.882
Confusion report [[862   8   5   4   6  59]
 [ 11 955   5   8   3   6]
 [  7   4 938 104  10   1]
 [ 25  29 158 818  55   7]
 [ 10  10  24  35 905  20]
 [ 68  24   4   2  11 927]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 5, Train loss: 0.018,  Val loss: 0.671
Train acc: 0.994, Val acc: 0.887
Confusion report [[837  22   2  13  12  58]
 [  8 955   3   8   4  10]
 [  3   2 891 156  11   1]
 [ 13  30 100 890  47  12]
 [  9   9   8  34 926  18]
 [ 65  17   8   2   6 938]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.013,  Val loss: 0.629
Train acc: 0.996, Val acc: 0.893
Confusion report [[849  10   7  10   5  63]
 [  7 956   4   7   2  12]
 [  3   0 911 137  13   0]
 [ 12  22 122 884  38  14]
 [  6   5  15  35 928  15]
 [ 44  23   8   3  15 943]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.013,  Val loss: 0.632
Train acc: 0.996, Val acc: 0.892
Confusion report [[858   7   4   5   6  64]
 [  5 953   4   2  11  13]
 [  5   1 924 121  12   1]
 [ 15  28 132 856  52   9]
 [  5   6  12  19 947  15]
 [ 65  21   5   4  11 930]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.011,  Val loss: 0.640
Train acc: 0.996, Val acc: 0.898
Confusion report [[847   9   3   6  13  66]
 [ 11 951   6   4   7   9]
 [  1   3 921 123  15   1]
 [ 10  26 102 897  50   7]
 [  3   6  16  20 946  13]
 [ 63  14   5   2   9 943]]
=> Saving a new best
learning_rate 0.001


100%|██████████| 3450/3450 [15:21<00:00,  3.74it/s]


Epoch: 9, Train loss: 0.010,  Val loss: 0.660
Train acc: 0.997, Val acc: 0.894
Confusion report [[853   8   5  10   9  59]
 [ 13 950   8   6   4   7]
 [  5   1 890 154  14   0]
 [ 15  10  89 920  49   9]
 [  5   7  12  46 917  17]
 [ 62  13   3   2  10 946]]
=> Validation loss did not improve
******************** Fold 6 **********


  0%|          | 0/3450 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.254,  Val loss: 0.449
Train acc: 0.909, Val acc: 0.859
Confusion report [[810   6   8   2  29  89]
 [  2 962   8   2   2  12]
 [ 11  26 869 108  34  16]
 [ 10  25 215 783  47  12]
 [  3   8  61  13 906   9]
 [ 46  30  18   1  12 929]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.103,  Val loss: 0.491
Train acc: 0.963, Val acc: 0.872
Confusion report [[858   8   6   2   8  62]
 [  1 959   4   7   7  10]
 [ 18  21 786 201  31   7]
 [ 19  24  83 925  28  13]
 [ 10   5  32  41 901  11]
 [ 78  33   6   1   8 910]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.055,  Val loss: 0.518
Train acc: 0.981, Val acc: 0.877
Confusion report [[876   4   4   2   9  49]
 [  2 957   8   1   8  12]
 [ 20  26 863 104  28  23]
 [  8  28 196 806  38  16]
 [  6   5  35  17 933   4]
 [ 76  14   2   0   7 937]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.036,  Val loss: 0.548
Train acc: 0.987, Val acc: 0.887
Confusion report [[827   3   9   2  13  90]
 [  0 971   1   7   4   5]
 [  5  31 880 114  21  13]
 [  5  17 127 899  31  13]
 [  2   9  57  17 913   2]
 [ 51  30   5   1   8 941]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.026,  Val loss: 0.555
Train acc: 0.991, Val acc: 0.889
Confusion report [[817   5  18   3  15  86]
 [  1 966   3   6   3   9]
 [  4  23 859 142  25  11]
 [  7  16 103 927  26  13]
 [  5   5  37  25 925   3]
 [ 44  20  11   0   8 953]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 5, Train loss: 0.016,  Val loss: 0.627
Train acc: 0.995, Val acc: 0.884
Confusion report [[864   4   4   6  16  50]
 [  0 961   2   7   7  11]
 [ 11  22 794 195  31  11]
 [ 11  23  79 947  29   3]
 [  3   5  22  32 936   2]
 [ 77  27   5   4  12 911]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.016,  Val loss: 0.675
Train acc: 0.995, Val acc: 0.886
Confusion report [[837   7   6   5  13  76]
 [  0 972   3   3   4   6]
 [  7  30 862 129  24  12]
 [ 11  16 101 916  31  17]
 [  7   9  48  45 889   2]
 [ 44  32   2   0  10 948]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.013,  Val loss: 0.609
Train acc: 0.996, Val acc: 0.897
Confusion report [[875   1   5   2   5  56]
 [  2 969   1   4   6   6]
 [ 15  21 889 110  21   8]
 [ 10  17 115 905  35  10]
 [  3   6  38  27 922   4]
 [ 77  16   3   1   4 935]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.010,  Val loss: 0.673
Train acc: 0.996, Val acc: 0.894
Confusion report [[871   2  10   2   8  51]
 [  2 969   4   4   3   6]
 [ 11  22 863 126  27  15]
 [ 11  22 103 915  29  12]
 [  6   8  22  38 922   4]
 [ 80  17   2   0   3 934]]
=> Validation loss did not improve
learning_rate 0.001


100%|██████████| 3450/3450 [15:25<00:00,  3.73it/s]


Epoch: 9, Train loss: 0.008,  Val loss: 0.632
Train acc: 0.997, Val acc: 0.905
Confusion report [[866   3   3   0  19  53]
 [  0 973   1   5   2   7]
 [ 12  23 876 107  35  11]
 [ 11   7 114 915  33  12]
 [  2   5  12  16 962   3]
 [ 61  13   3   0   8 951]]
=> Saving a new best
******************** Fold 7 **********


  0%|          | 0/3450 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.254,  Val loss: 0.400
Train acc: 0.910, Val acc: 0.877
Confusion report [[825  13   1   1  28  76]
 [  0 953   6  11   9   9]
 [  4  11 851 141  42  15]
 [  5  10 134 860  76   7]
 [  4  15  21  28 926   6]
 [ 48   7   5   5  18 953]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.099,  Val loss: 0.450
Train acc: 0.965, Val acc: 0.883
Confusion report [[858   9   0   0  18  59]
 [  3 951   5  11  10   8]
 [ 14  11 874 129  30   6]
 [ 12   7 128 865  72   8]
 [  9  13  18  26 924  10]
 [ 59  10  10   1  21 935]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.056,  Val loss: 0.452
Train acc: 0.980, Val acc: 0.889
Confusion report [[857   9   2   1   8  67]
 [  1 963  10   8   4   2]
 [  2  13 913 105  18  13]
 [  8  10 168 876  22   8]
 [  9  17  23  61 883   7]
 [ 46  12   7   5  14 952]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.030,  Val loss: 0.501
Train acc: 0.990, Val acc: 0.889
Confusion report [[859   2   0   1   8  74]
 [  1 954   8   8   4  13]
 [  3   9 878 141  19  14]
 [  8   6 129 913  25  11]
 [ 17  19  27  57 870  10]
 [ 55   2   4   0   5 970]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.024,  Val loss: 0.583
Train acc: 0.992, Val acc: 0.890
Confusion report [[861   2   1   4   8  68]
 [  0 970   3   6   4   5]
 [  1  16 847 173  12  15]
 [  4   9  89 973  11   6]
 [  6  23  43  82 837   9]
 [ 49   5   3   8   9 962]]
=> Saving a new best
learning_rate 0.001


100%|██████████| 3450/3450 [16:53<00:00,  3.40it/s]


Epoch: 5, Train loss: 0.020,  Val loss: 0.548
Train acc: 0.993, Val acc: 0.900
Confusion report [[849   7   0   5  18  65]
 [  0 965   0   8   9   6]
 [  4  14 905 114  19   8]
 [  2   7 143 904  31   5]
 [  4   9  27  39 917   4]
 [ 36   7   8   1  15 969]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.013,  Val loss: 0.570
Train acc: 0.995, Val acc: 0.901
Confusion report [[854  12   2   1  16  59]
 [  0 971   5   6   5   1]
 [  6  13 919 106  12   8]
 [  2   9 136 914  25   6]
 [  7  17  27  45 897   7]
 [ 39  10   7   0  18 962]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.013,  Val loss: 0.543
Train acc: 0.995, Val acc: 0.901
Confusion report [[874   7   0   1  10  52]
 [  0 969   3   9   5   2]
 [  2  11 905 116  17  13]
 [  7   3 138 913  26   5]
 [ 13  15  24  42 902   4]
 [ 55   7   6   0  16 952]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.008,  Val loss: 0.555
Train acc: 0.997, Val acc: 0.908
Confusion report [[881   2   2   1   6  52]
 [  1 958   8   6  10   5]
 [  5   8 921 113  10   7]
 [  7   2 113 940  23   7]
 [  8  13  28  39 909   3]
 [ 59   2   7   2  13 953]]
=> Saving a new best
learning_rate 0.001


100%|██████████| 3450/3450 [20:04<00:00,  2.86it/s]


Epoch: 9, Train loss: 0.007,  Val loss: 0.588
Train acc: 0.997, Val acc: 0.905
Confusion report [[874   0   0   0   8  62]
 [  2 961   2   5  13   5]
 [  7  12 891 118  22  14]
 [  8   6 115 931  25   7]
 [ 11   8  18  36 922   5]
 [ 46   5   4   1  16 964]]
=> Validation loss did not improve
******************** Fold 8 **********


  0%|          | 0/3450 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.253,  Val loss: 0.449
Train acc: 0.912, Val acc: 0.878
Confusion report [[843  15   4   8   5  69]
 [  0 952   5   7  15   9]
 [  2   9 824 162  65   2]
 [  6  16 116 905  44   5]
 [  8   9  29  31 918   5]
 [ 61  13   4  20   3 935]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.101,  Val loss: 0.461
Train acc: 0.964, Val acc: 0.883
Confusion report [[822   8   5   5   9  95]
 [  0 961   4   7   9   7]
 [  0   9 837 183  31   4]
 [  6  16 109 901  49  11]
 [ 12   5  32  40 905   6]
 [ 32   7   2   8   3 984]]
=> Saving a new best
learning_rate 0.001


100%|██████████| 3450/3450 [16:39<00:00,  3.45it/s]


Epoch: 2, Train loss: 0.052,  Val loss: 0.537
Train acc: 0.982, Val acc: 0.889
Confusion report [[857   9   6   3   6  63]
 [  0 966   5   3   5   9]
 [  0   9 903 110  37   5]
 [  1  21 162 855  44   9]
 [ 11   8  45  33 897   6]
 [ 55   8   1   4   1 967]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.034,  Val loss: 0.585
Train acc: 0.989, Val acc: 0.883
Confusion report [[850   8   3   2   6  75]
 [  3 946   3   5   9  22]
 [  6   6 883 110  43  16]
 [ 10  19 143 841  60  19]
 [ 10   6  26  35 909  14]
 [ 44   3   1   7   2 979]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.018,  Val loss: 0.596
Train acc: 0.994, Val acc: 0.888
Confusion report [[861   8   1   1   6  67]
 [  1 959   4   4  13   7]
 [  5  13 885 128  30   3]
 [  7  16 161 870  32   6]
 [ 14   1  32  58 889   6]
 [ 49   1   1   7   1 977]]
=> Validation loss did not improve
learning_rate 0.001


100%|██████████| 3450/3450 [16:32<00:00,  3.48it/s]


Epoch: 5, Train loss: 0.015,  Val loss: 0.627
Train acc: 0.995, Val acc: 0.890
Confusion report [[878  14   6   1   7  38]
 [  1 964   7   3   8   5]
 [  2   7 925  99  28   3]
 [  7  18 182 835  48   2]
 [ 13   3  41  21 920   2]
 [ 86   5   5   6   3 931]]
=> Saving a new best


  0%|          | 0/3450 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.015,  Val loss: 0.670
Train acc: 0.995, Val acc: 0.893
Confusion report [[852   8   6   1  10  67]
 [  1 960   1   5  15   6]
 [  1  10 903 114  33   3]
 [  5  10 148 885  38   6]
 [  8   2  33  43 908   6]
 [ 57   3   4   8   1 963]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.012,  Val loss: 0.616
Train acc: 0.996, Val acc: 0.895
Confusion report [[854  13   1   1  11  64]
 [  0 966   6   3   8   5]
 [  5   8 884 134  32   1]
 [  4  13 127 907  31  10]
 [ 12   5  19  54 904   6]
 [ 61   4   1   6   1 963]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.011,  Val loss: 0.637
Train acc: 0.996, Val acc: 0.896
Confusion report [[870   3   5   1   7  58]
 [  2 968   1   5   7   5]
 [  4   7 908 117  28   0]
 [  4  11 153 879  39   6]
 [ 18   3  47  36 894   2]
 [ 48   6   4   6   1 971]]
=> Saving a new best
learning_rate 0.001


100%|██████████| 3450/3450 [15:32<00:00,  3.70it/s]


Epoch: 9, Train loss: 0.010,  Val loss: 0.652
Train acc: 0.997, Val acc: 0.897
Confusion report [[871   8   5   1  10  49]
 [  0 964   2   1  15   6]
 [  1  14 863 132  49   5]
 [  6  15 130 876  53  12]
 [  8   3  18  22 947   2]
 [ 50   5   1   4   2 974]]
=> Saving a new best
******************** Fold 9 **********


  0%|          | 0/3450 [00:00<?, ?it/s]

learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 0, Train loss: 0.255,  Val loss: 0.360
Train acc: 0.911, Val acc: 0.890
Confusion report [[ 780    3    4   12   11  134]
 [   3  921   19   11    3   31]
 [   1    5  913  107   30    8]
 [   2    5  122  935   20    8]
 [   6    3   41   44  897    9]
 [  24    4    2    1    2 1003]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 1, Train loss: 0.102,  Val loss: 0.374
Train acc: 0.963, Val acc: 0.894
Confusion report [[860   7   1   9  12  55]
 [  2 971   8   1   0   6]
 [  6   5 925  90  36   2]
 [  5   9 153 899  26   0]
 [  4  18  58  28 885   7]
 [ 76  19   2   3   1 935]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 2, Train loss: 0.051,  Val loss: 0.396
Train acc: 0.982, Val acc: 0.907
Confusion report [[849   3   3   5  19  65]
 [  0 968   7   5   0   8]
 [  0  10 925  97  25   7]
 [  0   9 150 921  11   1]
 [  1  10  50  30 907   2]
 [ 33  15   2   0   1 985]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 3, Train loss: 0.033,  Val loss: 0.420
Train acc: 0.989, Val acc: 0.901
Confusion report [[884   3   3   7   7  40]
 [  2 960  13   8   2   3]
 [  4   5 892 134  27   2]
 [  1  11 116 948  11   5]
 [ 10   2  48  34 901   5]
 [ 82   6   6   4   5 933]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 4, Train loss: 0.024,  Val loss: 0.460
Train acc: 0.992, Val acc: 0.905
Confusion report [[836   0   2   5  15  86]
 [  0 951  11   8   5  13]
 [  1   3 927 103  27   3]
 [  0   7 139 930  12   4]
 [  4   1  48  35 908   4]
 [ 27   4   3   4   6 992]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 5, Train loss: 0.018,  Val loss: 0.420
Train acc: 0.994, Val acc: 0.914
Confusion report [[872   6   2   6  12  46]
 [  1 982   2   0   0   3]
 [  3  10 922  85  38   6]
 [  1   7 139 922  22   1]
 [  3   4  33  22 934   4]
 [ 58   7   2   1   2 966]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 6, Train loss: 0.014,  Val loss: 0.450
Train acc: 0.995, Val acc: 0.916
Confusion report [[869   0   3   5  14  53]
 [  1 977   2   5   0   3]
 [  1   8 923  95  34   3]
 [  0   7 124 929  25   7]
 [  7   4  25  27 936   1]
 [ 44  10   1   1   7 973]]
=> Saving a new best
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 7, Train loss: 0.013,  Val loss: 0.470
Train acc: 0.996, Val acc: 0.906
Confusion report [[857   2   2   4  18  61]
 [  0 977   5   2   0   4]
 [  5   3 877 118  53   8]
 [  5   6 120 910  45   6]
 [ 10   3  19  28 932   8]
 [ 34   2   0   3   1 996]]
=> Validation loss did not improve
learning_rate 0.001


  0%|          | 0/3450 [00:00<?, ?it/s]

Epoch: 8, Train loss: 0.011,  Val loss: 0.451
Train acc: 0.996, Val acc: 0.915
Confusion report [[885   0   1   9  11  38]
 [  0 976   2   6   0   4]
 [  4   6 906 100  45   3]
 [  2   7 116 940  19   8]
 [  8   3  28  22 935   4]
 [ 62  12   2   0   1 959]]
=> Validation loss did not improve
learning_rate 0.001


100%|██████████| 3450/3450 [15:25<00:00,  3.73it/s]


Epoch: 9, Train loss: 0.008,  Val loss: 0.464
Train acc: 0.997, Val acc: 0.915
Confusion report [[854   1   1  12  11  65]
 [  0 979   0   5   0   4]
 [  1   7 929  95  25   7]
 [  0   8 127 938   9  10]
 [  9   4  31  38 911   7]
 [ 34   8   1   1   1 991]]
=> Validation loss did not improve


In [15]:
test_file_list = create_file_list(test_data)
print(len(test_file_list))

7301


In [16]:
def predict_model(model, weight_path, dataloader_test, result_path, fname):
    submission=test_data
    all_predictions = []
    numpy_preds = []
    checkpoint = torch.load(weight_path)
    start_epoch = checkpoint['epoch']
    best_accuracy = checkpoint['best_acc']
    model.load_state_dict(checkpoint['state_dict'])
    model.eval()
    for image in tqdm.tqdm(dataloader_test):
        image = image.type(torch.FloatTensor).cuda()
        y_pred = F.softmax(model(Variable(image)))
        _,predicted = torch.max(y_pred,1)
        all_predictions.extend(predicted.cpu().data.numpy())
        numpy_preds.extend(y_pred.cpu().data.numpy())
    with open(numpy_dir+"{}{}_{}.pkl".format(result_path,fname,i), 'wb') as f:
        pickle.dump(numpy_preds, f)
    submission["label"]=all_predictions
    submission.to_csv(RESULTS+"{}{}_{}.csv".format(result_path,fname,i),index=False)

In [ ]:
model_name = "resnet34"
model = make_model(model_name, num_classes=6, pretrained=True, input_size=(150, 150))#, dropout_p=0.5)
model = model.to("cuda")
saved_folders = "{}/".format(model_name)#, "resnet50/", "se_resnet50/"]:
for trans, name in zip([no_transforms, train_transforms, train_transforms2, train_transforms3],
             ["no_transforms", "train_transforms", "train_transforms2", "train_transforms3"]):
    test_dataset = AVDataset(IMG_DIR, test_file_list, is_test = True, transform=trans)
    dataloader_test = data.DataLoader(test_dataset, batch_size = 16)
    for i,weights in enumerate(os.listdir(MODEL_DIR+saved_folders)):
        predict_model(model, MODEL_DIR+saved_folders+weights, dataloader_test, saved_folders, name)

  0%|          | 0/457 [00:00<?, ?it/s]/home/mukesh/miniconda3/envs/tgs_torch/lib/python3.6/site-packages/ipykernel_launcher.py:12: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  if sys.path[0] == '':
 30%|██▉       | 137/457 [00:28<01:06,  4.81it/s]